controllers:
    resource:
        path: ../src/Share/Infrastructure/Controller/
        namespace: App\Shared\Infrastructure\Controller
    type: attribute

kernel:
    resource: ../src/Share/Infrastructure/Kernel.php
    type: attribute
